spring.application.name=contact-backend

# ==========================
# DATABASE CONFIGURATION
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/internship_db
spring.datasource.username=root
spring.datasource.password=Gaurav@3451
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA CONFIGURATION
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# SERVER
# ==========================
server.port=8080